MASTER_CANVAS_WIDTH = 1890
MASTER_CANVAS_HEIGHT = 970
MASTER_CANVAS_BACKGROUND_COLOR = '#feffc4'
HOLD_LEFT_CLICK = '<B1-Motion>'
RELEASE_LEFT_CLICK = '<ButtonRelease-1>'
NODE_WIDTH = 64
NODE_HEIGHT = 64